service: graphql-blog-post-api

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: ${opt:stage, 'local'}

functions:
  graphql:
    handler: handlers.server
    events:
      - http:
          method: post
          path: graphql
          cors: true
  playground:
    handler: handlers.playground
    events:
      - http:
          method: get
          path: /
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
